name: Compilar Suc Softwares

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Permite rodar manualmente se precisar

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Baixando Arquivos
      uses: actions/checkout@v4

    - name: Configurando MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restaurando dependencias
      run: msbuild -t:restore

    - name: Criando o EXE (Release)
      run: msbuild SucSoftwares.csproj /p:Configuration=Release /p:Platform="Any CPU"

    - name: Disponibilizar para Download
      uses: actions/upload-artifact@v4
      with:
        name: Suc-Softwares-Pronto
        path: |
          **/*.exe
          **/*.dll
